### ISSUE TITLE
The CLI Package Should Be Published to GitHub Packages

### ISSUE THREAD

**Issue by egeuysall** [egeuysall/astra#7]
I see that you want to start from scratch with publishing your "astui" UI library to GitHub Packages. Let's go through the process step by step.

### 1. Configure Your package.json

First, ensure your package.json includes the GitHub-specific configurations:

```json name=package.json
{
  "name": "@egeuysall/astui",
  "version": "1.0.0",
  "description": "Your UI library description",
  "publishConfig": {
    "registry": "https://npm.pkg.github.com"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/egeuysall/astui.git"
  }
}
```

Make sure to:
- Scope your package name with your GitHub username: `@egeuysall/astui`
- Include the correct repository URL that points to your GitHub repo

### 2. Set Up Authentication

You'll need a Personal Access Token (PAT) with the right permissions:

1. Go to GitHub.com → Click your profile photo → Settings
2. In the left sidebar, click Developer settings → Personal access tokens → Fine-grained tokens
3. Click "Generate new token"
4. Give it a name like "GitHub Packages Publishing"
5. Set expiration as needed
6. Select your repository access (either "All repositories" or select specific ones)
7. Under "Repository permissions", find "Packages" and select "Read and write"
8. Click "Generate token"
9. **Important**: Copy the token immediately as you won't be able to see it again!

### 3. Configure Authentication for npm

Create or update your `.npmrc` file in your project root:

```text name=.npmrc
@egeuysall:registry=https://npm.pkg.github.com
//npm.pkg.github.com/:_authToken=YOUR_GITHUB_TOKEN
```

Replace `YOUR_GITHUB_TOKEN` with the token you generated.

Alternatively, you can log in via the npm CLI:

```bash
npm login --scope=@egeuysall --registry=https://npm.pkg.github.com
```

When prompted, enter:
- Username: your GitHub username (egeuysall)
- Password: your GitHub PAT (not your GitHub password)
- Email: your email address

### 4. Publish Your Package

Once your package.json and authentication are configured, you can publish:

```bash
npm publish
```

### 5. Optional: Set Up GitHub Actions for Automated Publishing

If you want to automate publishing whenever you push changes, create a GitHub Actions workflow:

1. Create a directory `.github/workflows` in your repository
2. Create a file named `publish.yml` with the following content:

```yaml name=.github/workflows/publish.yml
name: Publish Package to GitHub Packages

on:
  push:
    branches: [ main ]  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@egeuysall'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build  # Replace with your build command if different
      
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

This workflow uses the built-in `GITHUB_TOKEN` secret that's automatically available in GitHub Actions.

### 6. Using Your Package

After publishing, you and others can install your package from GitHub Packages:

```bash
# Add this to .npmrc
@egeuysall:registry=https://npm.pkg.github.com
//npm.pkg.github.com/:_authToken=YOUR_GITHUB_TOKEN

# Then install
npm install @egeuysall/astui
```

Would you like more information about any specific part of this process?
